name: Delete Stale Branches

on:
  schedule:
    - cron: '45 6 * * *' # Runs every day at mentioned UTC time
  workflow_dispatch:

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Delete stale branches
        uses: peter-evans/delete-branch@v3
        with:
          branches: |
            stale-branches
          age: 5 days
          dry-run: true 
