# This Github actions file will delete branches older than 15 days 

name: "Delete stale branches older than 15 days"

on:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest

    steps:
      # Run a set of commands using the runners shell
      - name: Run a one-off command
        run: |
          echo "This is a one-off command"
          echo "You can run any command here"
          echo "This is just an example"
          echo "You can also run scripts"

          
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          dry-run: false # Check out the console output before setting this to false
          exempt-organization: "acme-inc"
          exempt-authors-regex: "^dependabot"
          days-before-branch-stale: 15
          days-before-branch-delete: 15
          exempt-protected-branches: true 
